### ISSUE TITLE
Can I use the Datasets for the VIGOR live SIM reconstruction in this plugin?

### ISSUE THREAD

**Issue by eaglekindoms** [fairSIM/fairSIM-VIGOR#1]
Hello,
I want to research the  VIGOR live SIM reconstruction, and I have downloaded some datasets on [Zenodo](https://zenodo.org/record/3295829).
But I don't know how to use it, so are  there any tutorials? just like [fairsim](http://www.fairsim.org/screencasts/).

Thanks

**Comment by mueller-physics** [comment]
Hi, sorry for the late reply.
The datasets on Zenodo are already converted to TIFF files, so you can use a standard fairSIM installation (together with the time-lapse feature) to reconstruct them.
fairSIM VIGOR with GPU support is currently only supported when using the software in live reconstruction mode, and requires some installation & setup. We aim to eventually provide GPU support in a standard fairSIM installation, but are currently lacking the development resources to make that happen.

**Comment by eaglekindoms** [comment]
Thanks for your reply, I will try it on the standard fairSIM installation, and I will also learn how the GPU-accelerated code of fairSIM VIGOR works.
